export enum UrlConfig {
  PROMOTIONAL_BLOCKS = "/promotional-blocks",
  CATEGORIES = "/category-types",
  PRODUCTS = "/products-items",
  ORDERS = "/orders",
  AD_BLOCKS = "/ad-blocks",
  PROMO_CODES = "/promo-codes",
  CONFIGURATIONS = "/configurations",
  SHOPS = "/shops",
  COLORS = "/colors",
  SIZES = "/sizes",
  FUNCTIONALITIES = "/functionalities",
  DESIGNS = "/designs",
  USER_PAYMENTS = "/user-payments",
  USERS = "/users",
  APP_CONFIGURATIONS = "/app-configurations",
  SUBSCRIBERS_MESSAGES = "/subscribers-messages",
  TEMPLATES = "/templates",
}
